/*global systemDictionary:true */
'use strict';

systemDictionary = {
  'toyota adapter settings': {
    en: 'Adapter settings for toyota',
    de: 'Adaptereinstellungen für toyota',
    ru: 'Настройки адаптера для toyota',
    pt: 'Configurações do adaptador para toyota',
    nl: 'Adapterinstellingen voor toyota',
    fr: "Paramètres d'adaptateur pour toyota",
    it: "Impostazioni dell'adattatore per toyota",
    es: 'Ajustes del adaptador para toyota',
    pl: 'Ustawienia adaptera dla toyota',
    'zh-cn': 'toyota的适配器设置',
  },
  'App Email': {
    en: 'App Email',
    de: 'App-E-Mail',
    ru: 'Электронная почта приложения',
    pt: 'Email do aplicativo',
    nl: 'App-e-mail',
    fr: "Courriel de l'application",
    it: "E-mail dell'app",
    es: 'Correo electrónico de la aplicación',
    pl: 'E-mail aplikacji',
    'zh-cn': '应用电子邮件',
  },
  'App Password': {
    en: 'App Password',
    de: 'App-Passwort',
    ru: 'Пароль приложения',
    pt: 'Senha de app',
    nl: 'App-wachtwoord',
    fr: "Mot de passe de l'application",
    it: "Password dell'app",
    es: 'Contraseña de la aplicación',
    pl: 'Hasło do aplikacji',
    'zh-cn': '应用密码',
  },
  'Update interval (in minutes)': {
    en: 'Update interval (in minutes)',
    de: 'Aktualisierungsintervall (in Minuten)',
    ru: 'Интервал обновления (в минутах)',
    pt: 'Intervalo de atualização (em minutos)',
    nl: 'Update-interval (in minuten)',
    fr: 'Intervalle de mise à jour (en minutes)',
    it: 'Intervallo di aggiornamento (in minuti)',
    es: 'Intervalo de actualización (en minutos)',
    pl: 'Interwał aktualizacji (w minutach)',
    'zh-cn': '更新间隔（分钟）',
  },
  'Fetch Trips': {
    en: 'Fetch Trip Data',
    de: 'Trip Daten abrufen',
    ru: 'Получить данные Trip',
    pt: 'Dados de viagem',
    nl: 'Reisgegevens ophalen',
    fr: 'Récupération des données de voyage',
    it: 'Dati di viaggio a pagamento',
    es: 'Datos de viaje',
    pl: 'Pobierz dane dotyczące podróży',
    uk: 'Fetch Trip Дані',
    'zh-cn': '获取 Trip 数据',
  },
};
